#!/bin/bash

# Custom script to check if an email address has expired. The expected input
# data is provided by Exim from /etc/ealiases

if [[ "$#" -lt 2 ]]; then
 exit 0;
fi

EMAIL=$1
EALIASES=$2

MATCH=$(cat "$EALIASES" | grep "^$EMAIL:" | head -1)
IFS=' ' read -r -a SPLIT <<< "$MATCH"
if [[ "${#SPLIT[@]}" -ne 3 ]]; then
  exit 0;
fi

TARGET="${SPLIT[1]}"
EXPIRATION="${SPLIT[2]}"

if [[ "$EXPIRATION" =~ "N/A" ]]; then
  echo "$TARGET"
elif [[ "$EXPIRATION" -ge $(date +%s) ]]; then
  echo "$TARGET"
else
  echo ":fail: Temporary email address has expired."
fi
